### ISSUE TITLE
proof section not closed

### ISSUE THREAD

**Issue by scoskey** [pkra/laml#23] opened 2018-01-15 04:56 UTC
In vatter.html, rendered in-browser

**Comment by scoskey** [comment] 2018-01-15 05:37
Special case of #2. Problem is with commonmark rules. Goes away after adding a newline before </proof>. Only happens here because it's a statement with more than one paragraph.

**Comment by pkra** [comment] 2018-01-15 07:26
Yeah, I had noticed that, too. I agree it's a duplicate of #2.

**Closed as completed** 2018-01-15 23:06 UTC
Labels: duplicate
